name = "A2K-VANILLA-CLIENT-SD"
author = "A2KLAB"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "60e2199858603402c134c619d710aa9fdd657146d3637da066c775f8a86a924d"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"

[options]
acceptable-game-versions = ["1.21.5"]
