name = "A2K-VANILLA-CLIENT-SD"
author = "A2KLAB"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b611e92c6a3eb9ac90e3a2677393cdb5bd2251dbb0be0b12fd57c6a94169d8c9"

[versions]
fabric = "0.16.7"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
